COLUMN_COUNT				equ 80

CRT_CTRL_ADDR_REG			equ 03d4h
CRT_CRTL_DATA_REG			equ	03d5h

CRT_CTRL_DATA_CURBEGIN		equ 0ah
CRT_CTRL_DATA_STARTADDR_H	equ	0ch
CRT_CTRL_DATA_STARTADDR_L	equ	0dh
CRT_CTRL_DATA_CURSORPOS_H	equ	0eh
CRT_CTRL_DATA_CURSORPOS_L	equ	0fh